version: '3'
services:
  database:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: user123
      POSTGRES_DB: blogdb
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app-blog-backend:
    image: hp171100/blog-backend:01
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - database
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user123
      DB_PASSWORD: postgres
      DB_NAME: blogdb
    volumes:
      - ./backend/uploads:/app/uploads
  
  app-blog-frontend:
    image: hp171100/blog-frontend:01
    ports:
      - "5173:5173"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
      driver: bridge

  